### ISSUE TITLE
Feature idea: open notebook directly

### ISSUE THREAD

**Issue by takluyver** [Carreau/open-with-binder-firefox-extension#1]
On binder, you can specify a path to a notebook when launching. If the user is looking at a notebook when they click the button, it could open binder directly to that notebook.

**Comment by Carreau** [comment]
Yep, same if they browse a specific commit, branch or tag, which it does not do yet :-)

**Comment by Carreau** [comment]
Released with those features. See [here](https://addons.mozilla.org/en-US/firefox/addon/open-with-binder/) to install.
