### ISSUE TITLE
Identify branch from URL

### ISSUE THREAD

**Issue by RaoOfPhysics** [Carreau/open-with-binder-firefox-extension#8]
Thanks for the super-nice add-on!

I noticed that if you call the extension when you're browsing a feature branch, it doesn't detect the `tree` in the URL, and launches Binder with `master`. Can this be tweaked so the appropriate branch gets called in Binder?

Thanks, once again!

**Comment by Carreau** [comment]
Yes, that's the plan, and I believe also discussed in issue #1 ! I think I have it working I need to do a couple of sanity checks first.

**Comment by RaoOfPhysics** [comment]
@Carreau: Excellent! Please close this issue, then, if it's easier to track everything under #1. Thanks!

**Comment by Carreau** [comment]
Released, you can head [there](https://addons.mozilla.org/en-US/firefox/addon/open-with-binder/) and click install to update to the new version. Let me know if there are bugs.

**Comment by RaoOfPhysics** [comment]
Works like a charm! :D
